In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

In [5]:
a.ndim

1

In [6]:
a.nbytes

24

In [7]:
b = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
b[0,4]

5

In [9]:
b[: ,2]

array([ 3, 10])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2, 3, 3, 2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [13]:
np.ones((4, 2), dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [15]:
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [17]:
np.random.rand(4, 3)

array([[0.34393394, 0.4946754 , 0.59395762],
       [0.14139075, 0.45604757, 0.96133509],
       [0.9335227 , 0.65393891, 0.38068172],
       [0.43339924, 0.13999676, 0.4897776 ]])

In [19]:
np.random.randint(7, size=(3, 3))

array([[0, 6, 4],
       [2, 0, 1],
       [6, 4, 0]])

In [22]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
arr = np.array([[1, 2, 3]])

In [39]:
rl = np.repeat(arr, 3, axis = 0)

In [40]:
print(rl)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [46]:
arr = np.ones((5, 5))

In [47]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
z = np.zeros((3, 3))

In [49]:
z[1,1] = 9

In [50]:
arr[1:-1, 1:-1] = z

In [51]:
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [52]:
a = np.array([1, 2, 3, 4])

In [53]:
a-1

array([0, 1, 2, 3])

In [54]:
a-5

array([-4, -3, -2, -1])

In [55]:
a ** 3

array([ 1,  8, 27, 64])

In [56]:
stats = np.array([1, 5, 6, 90, 100])

In [57]:
np.min(stats)

1

In [58]:
before = np.array([[1, 4, 5],[3, 4, 5]])

In [59]:
print(before)

[[1 4 5]
 [3 4 5]]


In [62]:
after = before.reshape((3,2))

In [63]:
after

array([[1, 4],
       [5, 3],
       [4, 5]])

In [64]:
v1 = np.array([1, 4, 3, 5])

In [65]:
v2 = np.array([6, 7, 10, 90])

In [67]:
np.vstack([v1,v2,v1,v1-1])

array([[ 1,  4,  3,  5],
       [ 6,  7, 10, 90],
       [ 1,  4,  3,  5],
       [ 0,  3,  2,  4]])